package com.myclinic.part2project.controllers;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.myclinic.part2project.model.Patient;
import com.myclinic.part2project.model.Payment;
import com.myclinic.part2project.model.Staff;
import com.myclinic.part2project.service.PatientService;
import com.myclinic.part2project.service.PaymentService;
import com.myclinic.part2project.service.StaffService;

/**
 * A Spring controller that allows the users to download a PDF document
 * generated by the iText library.
 * 
 * @author www.codejava.net
 * 
 */
@Controller
public class ReportController {

	@Autowired
	PatientService patientService;

	@Autowired
	StaffService staffService;

	@Autowired
	PaymentService paymentService;

	@GetMapping(value = "/getReportPage")
	public String getReportPage(Model theModel) {
		return "report";
	}

	@RequestMapping(value = "/patientReports", method = RequestMethod.GET)
	public ModelAndView patientReport() {
		List<Patient> patients = patientService.getPatients();
		return new ModelAndView("patientPdfView", "listPatients", patients);
	}

	@GetMapping(value = "/staffReports")
	public ModelAndView staffReports() {
		List<Staff> staffs = staffService.getStaffs();
		return new ModelAndView("staffPdfView", "listStaffs", staffs);
	}

	@GetMapping(value = "/paymentReports")
	public ModelAndView paymentReports() {
		List<Payment> payments = paymentService.getPayments();
		return new ModelAndView("paymentPdfView", "listPayments", payments);
	}

}